# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starship',
            name='cargo_capacity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='starship',
            name='crew',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='starship',
            name='hyperdrive_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='starship',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='starship',
            name='passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
