# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0002_auto_20190515_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_listed',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
